@path = 

### Get home page
GET {{baseUrl}}/{{path}}
Authorization: Bearer {{token}}

### Get status page
GET {{baseUrl}}/status
Authorization: Bearer {{token}}

### Get types
GET {{baseUrl}}/types
Authorization: Bearer {{token}}