@path = robots

########## CREATE
POST {{baseUrl}}/{{path}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Robô 4125", 
  "lifetime": "120000", 
  "operationCycleTime": "10000", 
  "tradeMarket": "cryptocurrencies", 
  "initialCapital": "1000", 
  "stopLoss": "5", 
  "stopGain": "0", 
  "brokerId": "67bc8543e956e02e35f87245", 
  "tradeStrategyId": [ 
    "67bc8519e956e02e35f87240",
    "67bcae581395f7776679b009"
  ],
  "currencySymbol": "BTCUSDT", 
  "otherParams": [ 
    {
      "name": "limit",
      "key": "limit",
      "type": "string",
      "description": "",
      "value": "100"
    },
    {
      "name": "interval",
      "key": "interval",
      "type": "string",
      "description": "",
      "value": "15m"
    }
  ],
  "simulationMode": false
}

########## GET ALL
GET {{baseUrl}}/{{path}}
Authorization: Bearer {{token}}

########## GET BY ID
GET {{baseUrl}}/{{path}}/67d0c11d895b4f4dfd995e2f
Authorization: Bearer {{token}}

########## UPDATE
PUT {{baseUrl}}/{{path}}/67bc8557e956e02e35f87249
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "tradeStrategyId": [ 
    "67bc8519e956e02e35f87240",
    "67bcae581395f7776679b009"
  ]
}

########## DELETE
DELETE {{baseUrl}}/{{path}}/67b0ad58d30d5e764b2ae398
Authorization: Bearer {{token}}

###################################################################################
##### ACTIONS #####################################################################
###################################################################################
########## START
PUT {{baseUrl}}/{{path}}/67bc8557e956e02e35f87249/startRobot
Authorization: Bearer {{token}}
########## STOP
PUT {{baseUrl}}/{{path}}/67bc8557e956e02e35f87249/stopRobot
Authorization: Bearer {{token}}
########## KILL
PUT {{baseUrl}}/{{path}}/67bc8557e956e02e35f87249/killRobot
Authorization: Bearer {{token}}