@path = users

########## CREATE
POST {{baseUrl}}/{{path}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Rodrigo Pimentel 2",
  "role": "administration",
  "email": "pimentelmsn2@hotmail.com",
  "password": "12345"
}

########## GET ALL
GET {{baseUrl}}/{{path}}
Authorization: Bearer {{token}}

########## GET BY ID
GET {{baseUrl}}/{{path}}/67cb04eecfb092fc042de33d
Authorization: Bearer {{token}}

########## UPDATE
PUT {{baseUrl}}/{{path}}/67cb04eecfb092fc042de33d
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Rodrigo Pimentel - 2"
}

########## DELETE
DELETE {{baseUrl}}/{{path}}/67cb04eecfb092fc042de33d
Authorization: Bearer {{token}}